### ISSUE TITLE
The missing ReLU layer before GlobalMaxPool1D

### ISSUE THREAD

**Issue by liuyannan** [j40903272/MalConv-keras#1]
Dear j40903272,

Thank you very much for sharing the code!!

According to the picture on NVIDIA website(https://devblogs.nvidia.com/malware-detection-neural-networks/), there should be one ReLU layer after the multiply and before the GlobalMaxPool1D layer. This  ReLU seems not explicitly mentioned in the paper.

**Comment by j40903272** [comment]
Thanks !! Let's add it then.

According to the original paper, they tested several activation functions and get identical performance. You can try different activation functions as well.

Besides, the optimizer and parameters are not the same which the origin paper proposed. 
Original: SGD lr 0.01 momentum 0.9 exponential decay
I supposed that the optimizers may act differently on different datasets , so you could also choose your own optimizer too.
