### ISSUE TITLE
error with training the dataset

### ISSUE THREAD

**Issue by Alibm73-zz** [j40903272/MalConv-keras#5]
hi @j40903272 
I'm somewhat new to this so i apologize for my preliminary questions.
i can't seem to get the training phase to work.
when i type `python3 train.py mytrainset.csv` it says that the malware and benign files does not exist.
I have 400 malwares and 400 benign files which all of them are in `.bytes ` format. i placed them in the `MalConv-keras` directory in a file called `train`. then i made a csv file called `mytrainset.csv` (which is in the `MalConv-keras` directory).
so i have a couple of questions:
1 - what am i doing wrong?? or rather what should i do??
2- where should i put my malware of or benign files??
3- is the `.bytes` format OK or should i use different formats like `.asm` or `.exe` or ...
I look forward to your reply, thnx

**Comment by j40903272** [comment]
Hi, @Alibm73 
1,2 - It seems that train.py did not find your files. I'll suggest to change the path in mytrainset.csv into absolute path. This is the most straight forward way to solve the problem. 
3 - Any format would be fine and all of them should work well. However, different file type may provide different insight to Malconv model to learn.
