### ISSUE TITLE
I can not find datasets

### ISSUE THREAD

**Issue by YahyaAbraheem** [j40903272/MalConv-keras#6]
Hello,

I got error while training as I could not find the datasets mentioned in example.csv. 

`E:\dataset\malware\malware\fbd1a4b23eff620c1a36f7c9d48590d2fccda4c2_cc82281bc576f716d9a0271d206beb81ad078b53 not exist
E:\dataset\malware\malware\5746b9ed6b78d8f1cdb0b8bb9016624a46430346_007439fd0f1bfcb25e540a2b5ddbc96d7ea09afd not exist
E:\dataset\malware\malware\c095da034535f15a27c073dce54212a28e1af683_8e86441bc4f6a7fc492779caf280f1d769e0cd4d not exist
E:\dataset\malware\malware\3138cef67d651745c2db3744a70d6bf861e2a728_7b5ec86f006dc6d35d48821ca1311561bd86157a not exist
E:\dataset\malware\malware\3f3fc4ed6a51a4385de9a38b164bcc14a4334eac_20002faf28adfd94ca98cf6ced46f14334b53684 not exist
E:\dataset\malware\malware\80913fa3c7d18d89c47b42e929cf9c98729aa565_2dcb3285f944bc0b6e7cb7612dad360b9458ccdc not exist
E:\dataset\malware\malware\ead2a1884a52c93c654853d2891a1208ac6ee2b8_b75311ed885fb252554ab6dc228326d388043630 not exist
E:\dataset\malware\malware\19c625db4021d4934916f42b97777098b0b8cf15_0192ba11326fe2298c8cb4de616f4d4140213838 not exist
E:\dataset\malware\malware\2a7a2505e43decf3583ec11bbad6ead816ef1861_2906bffe07800fe9ff93d544bff8a46e56aa64d9 not exist
E:\dataset\malware\malware\488e5eea345e24440f7d0d2a32fbafda314ee6ca_df473c0493d503828157e32664e28357a4094f7a not exist
E:\dataset\malware\malware\c47ed37c0e1e8be110f889f5989aea6b1bb7fda4_42c3033e34d27c951f7db7ae6aa5f45b8ef472ac not exist
E:\dataset\malware\malware\0778a070b283d5f4057aeb3b42d58b82ed20e4eb_f205bd9628ff8dd7d99771f13422a665a70bb916 not exist
`
Can you please tell me where I can find and download them?

**Comment by 24mlight** [comment]
I found it is a problem too.........

**Comment by j40903272** [comment]
The path in example.csv does not provide the dataset but only provides an example of input csv file format. You'll have to download your own dataset and create a csv file in the same format with each row containing the path to your malware file.
